---
version: '3.6'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: bash -c "go build -o bin/api && bin/api"
    volumes:
      - .:/go/src/github.com/recipey/api
    environment:
      APP_DB_USERNAME: recipey
      APP_DB_PASSWORD: recipey
      APP_DB_NAME: recipey_dev
      APP_DB_URL: postgres://recipey:recipey@db:5432/recipey_dev?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_USER: recipey
      POSTGRES_PASSWORD: recipey
      POSTGRES_DB: recipey_dev

    # makes sure on every startup we don't lose data from
    # previous container shutting down so we persist data
    # to host env at ~/.data/postgresql
    volumes:
      - ~/.data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
